### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by dhassault** [anthcor/cloudrun-fastapi#11]
When deploying to Cloud Run, this error triggered: `ModuleNotFoundError: No module named python container tests`. 
`tests/` was indeed added to `.dockerignore`

**Comment by dhassault** [comment]
Fixed in https://github.com/anthcor/cloudrun-fastapi/pull/10

**Comment by anthcor** [comment]
this way factories are added https://github.com/anthcor/cloudrun-fastapi/blob/master/.dockerignore#L165
