### ISSUE TITLE
Cannot migrate to Cloud SQL

### ISSUE THREAD

**Issue by dhassault** [anthcor/cloudrun-fastapi#9]
Hi!

When I'm connecting to my cloud SQL instance with `psql "sslmode=disable host=/tmp/cloudsql/PROJECT_ID:REGION:INSTANCE_NAME user=postgres dbname=postgres"`, it works well but when using:
```
cloud_sql_proxy -instances=PROJECT_ID:REGION:INSTANCE_NAME -dir=/tmp/cloudsql
```
And then doing:
```
PYTHONPATH=. alembic revision --autogenerate -m "initial setup"
```
I have the error:
```
...
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'PROJECT_ID:REGION:INSTANCE_NAME'
```

(PROJECT_ID:REGION:INSTANCE_NAME being my own instance)

Any idea or documentation to solve this issue?

**Comment by anthcor** [comment]
hi there! [ive updated the docs to be more clear](https://github.com/anthcor/cloudrun-fastapi/tree/master/docs#working-with-postgres). make sure you've exported your project id `export PROJECT_ID=$(gcloud config get-value project)` in the shell where you're running the alembic commands. also id suggest trying to connect to the instance directly to make sure you can establish a connection. this makes me think that sqlalchemy isn't getting something like `"postgresql+psycopg2://postgres@localhost:5432/postgres"` – so maybe check that the `DATABASE_URL` you stored in google cloud secrets manager is the right url (you'll want that url to have the user password in it too). hope this helps!
